### PR TITLE
Adding new '?from=FileFormat' support for .css protocol hooks

### PR DESCRIPTION
**Pull request by carlrabbit**
Hi, 
I was running into an issue with recent (over a year?!) versions of *electron-compile*.

I thought that allowing (and parsing) query-string parameters is the best solution to the problem of the electron JS engine not allowing stylesheet-includes with a different file name than '.css' anymore.

If this solution is accepted, I would update the docs accordingly as well. Plus I would try to trigger updates in projects using us.

Kind regards,
Martin

### CODE REVIEW

**Comment by carlrabbit** [comment]
Hi,

the PR check seems to fail not because of my changes. Looks like the latest tests are broken?! 

How do we proceed from here?

KR,
Martin

**Comment by justintaddei** [comment]
I love this solution! Implementing locally until this is merged.

**Review by justintaddei — CHANGES_REQUESTED** [review]
Perhaps consider `/\.[a-z1-9]+$/i` in place of `/\.css$/i` so that it works with all file types?

**Comment by carlrabbit** [comment]
Sorry, this was messed up as I started reusing my repo.

**Pull request closed without merging**
